const columns = [
  {
    field: "jobNumber",
    headerName: "Job Number",
    headerAlign: "left",
    headerClassName: "header",
    width: 150,
  },
  {
    field: "customerName",
    headerName: "Customer Name",
    headerAlign: "left",
    headerClassName: "header",
    width: 200,
  },
  {
    field: "billingName",
    headerName: "Billing Name",
    headerAlign: "left",
    headerClassName: "header",
    width: 150,
  },
  {
    field: "jobDate",
    headerName: "Job Date",
    headerAlign: "left",
    headerClassName: "header",
    width: 150,
  },
  {
    field: "jobTimeSpecific",
    headerName: "Job Time Specific",
    headerAlign: "left",
    headerClassName: "header",
    width: 200,
  },
  {
    field: "jobTimeFrom",
    headerName: "Job Time From",
    headerAlign: "left",
    headerClassName: "header",
    width: 180,
  },
  {
    field: "jobTimeTo",
    headerName: "Job Time To",
    headerAlign: "left",
    headerClassName: "header",
    width: 150,
  },
  {
    field: "actualJobTimeSpecific",
    headerName: "Actual Job Time Specific",
    headerAlign: "left",
    headerClassName: "header",
    width: 250,
  },
  {
    field: "inProgressTime",
    headerName: "In Progress Time",
    headerAlign: "left",
    headerClassName: "header",
    width: 200,
  },
  {
    field: "jobAttemptCompletedDate",
    headerName: "Job Attempt Complete Date",
    headerAlign: "left",
    headerClassName: "header",
    width: 280,
  },
  {
    field: "jobTemplateName",
    headerName: "Job Template Name",
    headerAlign: "left",
    headerClassName: "header",
    width: 200,
  },
  {
    field: "driverName",
    headerName: "Driver Name",
    headerAlign: "left",
    headerClassName: "header",
    width: 150,
  },
  {
    field: "vehicleName",
    headerName: "Vehicle Name",
    headerAlign: "left",
    headerClassName: "header",
    width: 200,
  },
];

export default columns;
